export const DEPARTMENTS = [
  "English",
  "Linguistics",
  "History",
  "Philosophy",
  "Sociology",
  "Psychology",
  "Political Science",
  "International Relations",
  "Economics",
  "Anthropology",
  "Geography",
  "Social Work",
  "Gender Studies",
  "Media & Communication Studies",
  "Journalism",
  "Business Administration",
  "Management Sciences",
  "Accounting",
  "Finance",
  "Marketing",
  "Human Resource Management",
  "Entrepreneurship",
  "Supply Chain Management",
  "Business Economics",
  "Computer Science",
  "Software Engineering",
  "Information Technology",
  "Artificial Intelligence",
  "Data Science",
  "Cyber Security",
  "Electrical Engineering",
  "Electronics Engineering",
  "Mechanical Engineering",
  "Civil Engineering",
  "Mechatronics Engineering",
  "Biomedical Engineering",
  "Chemical Engineering",
  "Environmental Engineering",
  "Telecommunications Engineering",
  "Mathematics",
  "Statistics",
  "Physics",
  "Chemistry",
  "Biology",
  "Biotechnology",
  "Microbiology",
  "Biochemistry",
  "Environmental Sciences",
  "Earth Sciences",
  "Astronomy",
  "Medicine",
  "Surgery",
  "Nursing",
  "Pharmacy",
  "Public Health",
  "Physiotherapy",
  "Medical Laboratory Sciences",
  "Dentistry",
  "Nutrition & Dietetics",
  "Radiology",
  "Anesthesiology",
  "Education",
  "Curriculum & Instruction",
  "Educational Leadership",
  "Special Education",
  "Educational Psychology",
  "Law",
  "Legal Studies",
  "Criminal Justice",
  "International Law",
  "Architecture",
  "Interior Design",
  "Urban & Regional Planning",
  "Fine Arts",
  "Visual Arts",
  "Graphic Design",
  "Industrial Design",
  "Fashion Design",
  "Textile Design",
  "Agriculture",
  "Agronomy",
  "Horticulture",
  "Animal Sciences",
  "Veterinary Sciences",
  "Food Science & Technology",
  "Fisheries",
  "Forestry",
  "Islamic Studies",
  "Comparative Religion",
  "Theology",
  "Quran & Sunnah Studies",
  "Arabic Studies",
  "Sustainability Studies",
  "Climate Change",
  "Development Studies",
  "Peace & Conflict Studies",
  "Public Policy",
  "Innovation & Technology Management",
  "Digital Media",
  "Game Design",
  "Robotics",
];
